version: '3'

services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes: 
      - ./:/var/www/html
    ports: 
      - 3000:3000
    tty: true
    restart: always
    networks: 
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes: 
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    depends_on: 
      - backend
    tty: true
    restart: always
    networks: 
      - app

networks:
  app:
    driver: bridge