version: '3'

services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes: 
      - ./:/var/www/html
    ports: 
      - 3000:3000
    depends_on: 
      - database
    tty: true
    restart: always
    networks: 
      - app

  database:
    image: mysql:5.7
    container_name: database
    environment: 
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rahasia
      - MYSQL_DATABASE=node-app
    ports: 
      - 3306:3306
    tty: true
    restart: always
    networks: 
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes: 
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    depends_on: 
      - backend
    tty: true
    restart: always
    networks: 
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment: 
      - PMA_HOST=database
      - PMA_PORT=3306
    ports: 
      - 8080:80
    depends_on: 
      - database
    tty: true
    restart: always
    networks: 
      - app

networks:
  app:
    driver: bridge